# Generated by Django 4.2.4 on 2023-09-02 11:22

import IMDB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=IMDB.models.upload_image_filme),
        ),
    ]
